slide_duration: 5 # sec
slide_animation: cross-fade
slide_animation_duration: 2
audio: bgmusic.mp3
source: 'tmp/images/%d.jpg'
output:
  tmp_filename: tmp/movie.mp4
  filename: output/movie.mp4
  resolution: 1920x1080 #‘hd1080’
  height: 1080
  width: 1920
  frame_rate: '1/30' #‘sntsc’ '1/5'

caption:
  show: true
  font-family: Times New Roman
  font-color: red
  font-size: 30px;
  animation: slide-left

# The first frame
title:
  show: true
  font-family: Times New Roman
  font-color: red
  font-size: 30px;
  animation: slide-left